### ISSUE TITLE
Scss loader not working ? 

### ISSUE THREAD

**Issue by julienchazal** [rayfranco/bourgeon#5]
Hello

First thanks for this great template ;)

i tried to add 
```
  scss: {
    import: [
      path.resolve(__dirname, '../src/styles/index.scss')
    ]
  }
```
Inside `index.scss` i put `@import "helpers.scss";`
And inside `helpers.scss` i got my `clearfix` mixin

But when i try to use clearfix mixin inside a component i get this error : 
```
@include clearfix();
            ^
      No mixin named clearfix
```

I have to add `@import "../styles/helpers.scss";` inside my component to make it work.

Any idea please ?

**Comment by rayfranco** [comment]
Thanks for your feedback. Bourgeon is using Stylus and not supporting other preprocessors as is. But you could be able to easily achieve what you want by referring to your loader's documentation. For example with **sass-loader** https://github.com/webpack-contrib/sass-loader#imports

**Comment by julienchazal** [comment]
thx for your answer !
i had already installed node-sass and sass-loader.
it worked by adding this line to `build/utils.js` : 
`scss: generateLoaders(['css', 'sass?data=@import "~src/styles/index";']),`
but i still don't understand why this lines did not work in `build/webpack.base.conf.js` : 
```
 scss: {
    import: [
      path.resolve(__dirname, '../src/styles/index.scss')
    ]
  }
```
