### ISSUE TITLE
Mustache-like logic in templates?

### ISSUE THREAD

**Issue by davestewart** [rayfranco/bourgeon#7]
Hi there,

Was just checking out your project.

What is the mustache-like logic in the templates?
 
https://github.com/rayfranco/bourgeon/blob/master/template/src/components/Welcome.vue

Thanks,
Dave

**Comment by rayfranco** [comment]
Hello @davestewart this is a template for [vue-cli](https://github.com/vuejs/vue-cli) and the mustache-like logic is used for generating your project. It won't be visible once the project is generated.

**Comment by davestewart** [comment]
OK, thanks, good to know!
